screenshots + jobs

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -216,7 +216,7 @@ jobs:
                   # Your command
                   cd .circleci/ansible
                   ansible-playbook -i inventory.txt configure-server.yml
-          # Here's where you will add some code to rollback on failure
+          - destroy_environment
 
   run-migrations:
       docker:
@@ -251,6 +251,8 @@ jobs:
                       # If you are using kvdb.io, generate the bucket ID "9GE4jRtKznmVKRfvdBABBe" in your local terminal first
                       curl https://kvdb.io/Jg9tJadoirqbBsLsrvPAqN/migration_$\{CIRCLE_WORKFLOW_ID:0:7} -d '1'
                   fi
+          - destroy_environment
+          - revert-migrations
 
   deploy-frontend:
         docker:
@@ -290,7 +292,11 @@ jobs:
 
                     npm run build
                     tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
-                    aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
+                    aws s3 cp ./dist "s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7}" --recursive
+            - persist_to_workspace:
+                root: .
+                paths:
+                - frontend/dist
             # Here's where you will add some code to rollback on failure
             - destroy_environment
             - revert-migrations
@@ -342,6 +348,58 @@ jobs:
           - destroy_environment
           - revert-migrations
 
+  smoke-test:
+        docker:
+            # Lightweight Docker image
+            - image: node:13.8-buster
+        steps:
+            # Checkout code from git
+            - checkout
+            - run:
+                name: Update packages
+                command: |
+                    apt update
+            - run:
+                name: Install dependencies (Curl)
+                command: |
+                    apt-get -y install curl
+            - run:
+                name: Install dependencies (AWS-Cli)
+                command: |
+                    apt-get -y install awscli
+            - run:
+                name: Backend smoke test.
+                command: |
+                    BACKEND_IP=$(aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" --output text)
+                    echo "Backend-ip: ${BACKEND_IP}"
+                    API_URL="http://${BACKEND_IP}:3030"
+                    echo "API URL: ${API_URL}"
+
+                    # your code here
+                    # Fetch and prepare the BACKEND_IP env var
+                    if curl "${API_URL}/api/status" | grep "ok"
+                    then
+                        exit 0
+                    else
+                        exit 1
+                    fi
+            - run:
+                name: Frontend smoke test.
+                command: |
+                    # your code here
+                    URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"
+                    echo ${URL}
+                    if curl -s ${URL} | grep "Welcome"
+                    then
+                        # Change this to 0 after the job fails
+                        exit 0
+                    else
+                        exit 1
+                    fi
+            # Here's where you will add some code to rollback on failure
+            - destroy_environment
+            - revert-migrations
+
 workflows:
     default:
         jobs:
@@ -362,9 +420,9 @@ workflows:
                     only: [master]
         - configure-infrastructure:
             requires: [deploy-infrastructure]
-        - run-migrations:
-                requires: [configure-infrastructure]
         - deploy-frontend:
             requires: [deploy-infrastructure]
         - deploy-backend:
             requires: [deploy-infrastructure]
+        - smoke-test:
+                requires: [deploy-backend, deploy-frontend]
